server:
  port: 8001

spring:
  application:
    name: service-edu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 15717747056HYb!
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.1:8848

#    sentinel:
#      transport:
#        dashboard: localhost:8080
#        port: 8719 #表示与该微服务交互的端口,默认,可以不写8080是其sentinel控制台的端口
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  config: classpath:logback-spring.xml
mybatis-plus:
  mapper-locations: classpath:com/hyb/serviceedu/mapper/xml/*.xml
feign:
  sentinel:
    enabled: true

