server:
  port: 8008
spring:

  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 15717747056HYb!
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.1:8848
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞时间,负数表示没限制
        max-idle: 5
        min-idle: 0
    password: 123456
  rabbitmq:
    host: 192.168.188.100
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      # 只要抵达队列,以异步模式优先return确认
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
#  spring.rabbitmq.host=192.168.77.130
#  spring.rabbitmq.port=5672
#  # 虚拟主机配置
#  spring.rabbitmq.virtual-host=/
#  # 开启发送端消息抵达Broker确认
#  spring.rabbitmq.publisher-confirms=true
#  # 开启发送端消息抵达Queue确认
#  spring.rabbitmq.publisher-returns=true
#  # 只要消息抵达Queue，就会异步发送优先回调returnfirm
#  spring.rabbitmq.template.mandatory=true
#  # 手动ack消息，不使用默认的消费端确认
#  spring.rabbitmq.listener.simple.acknowledge-mode=manual