server:
  port: 8009

spring:
  application:
    name: service-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 15717747056HYb!
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.1:8848
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞时间,负数表示没限制
        max-idle: 5
        min-idle: 0
    password: 123456
default:
  captcha:
    width: 130
    height: 60
    length: 6
  codeTimeOut: 5
  avatar: https://edu-2022-2-21.oss-cn-beijing.aliyuncs.com/631c1de909b93377b3fa6eac7ed80d1.jpg