server:
  port: 8010

spring:
  application:
    name: service-count
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 15717747056HYb!
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.1:8848
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞时间,负数表示没限制
        max-idle: 5
        min-idle: 0
    password: 123456
  task:
    execution:
      # 异步任务默认线程池大小
      pool:
        core-size: 20