server:
  port: 4000

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/servicecms/**
    nacos:
      discovery:
        server-addr: 192.168.216.1:8848